// egypt_walls_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 21 total shaders

textures/egypt_walls_sd/stucco01_decor01_phong
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_walls_sd/stucco01_decor01.tga
}

textures/egypt_walls_sd/stucco01_phong
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_walls_sd/stucco01.tga
}

textures/egypt_walls_sd/stucco02
{
	qer_editorimage textures/egypt_walls_sd/stucco02.tga
	q3map_nonplanar
	q3map_shadeangle 60
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/egypt_walls_sd/stucco02.tga
		blendFunc filter
	}
}

textures/egypt_walls_sd/stucco02_04blend
{
	q3map_nonplanar
	q3map_shadeangle 30
	implicitMap -
}

textures/egypt_walls_sd/stucco03
{
	q3map_nonplanar
	q3map_shadeangle 60
	implicitMap -
}

textures/egypt_walls_sd/stucco04
{
	q3map_nonplanar
	q3map_shadeangle 60
	implicitMap -
}

textures/egypt_walls_sd/stucco07a
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco07a_nonsolid
{
	surfaceparm nonsolid
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_walls_sd/stucco07a
}

textures/egypt_walls_sd/stucco07b
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco07c
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco07d
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08a
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08b
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08c
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08d
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08e
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09a
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09b
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09c
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09d
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09e
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09f
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/wood_c05
{
	surfaceparm woodsteps
	implicitMap -
}

textures/egypt_walls_sd/wood_c06
{
	surfaceparm woodsteps
	implicitMap -
}

textures/egypt_walls_sd/wood_test
{
	surfaceparm woodsteps
	implicitMap -
}

//*********
//NEW - the previous segment should be checked for incompatibilties
//*********

textures/egypt_walls_sd/stucco08a
{
    qer_editorimage 	textures/egypt_walls_sd/stucco08a
	diffusemap			textures/egypt_walls_sd/stucco08a
	bumpmap        		displacemap( textures/egypt_walls_sd/stucco08a_norm, invertColor(textures/egypt_walls_sd/stucco08a_disp) )
	specularmap			textures/egypt_walls_sd/stucco08a_spec
	
}

textures/egypt_walls_sd/stucco08b
{
    qer_editorimage 	textures/egypt_walls_sd/stucco08b
	diffusemap			textures/egypt_walls_sd/stucco08b
	bumpmap        		displacemap( textures/egypt_walls_sd/stucco08b_norm, invertColor(textures/egypt_walls_sd/stucco08b_disp) )
	specularmap			textures/egypt_walls_sd/stucco08b_spec
	
}

textures/egypt_walls_sd/stucco08c
{
    qer_editorimage 	textures/egypt_walls_sd/stucco08c
	diffusemap			textures/egypt_walls_sd/stucco08c
	bumpmap        		displacemap( textures/egypt_walls_sd/stucco08c_norm, invertColor(textures/egypt_walls_sd/stucco08c_disp) )
	specularmap			textures/egypt_walls_sd/stucco08c_spec
	
}

textures/egypt_walls_sd/stucco08d
{
    qer_editorimage 	textures/egypt_walls_sd/stucco08d
	diffusemap			textures/egypt_walls_sd/stucco08d
	bumpmap        		displacemap( textures/egypt_walls_sd/stucco08d_norm, invertColor(textures/egypt_walls_sd/stucco08d_disp) )
	specularmap			textures/egypt_walls_sd/stucco08d_spec
	
}

textures/egypt_walls_sd/stucco08e
{
    qer_editorimage 	textures/egypt_walls_sd/stucco08e
	diffusemap			textures/egypt_walls_sd/stucco08e
	bumpmap        		displacemap( textures/egypt_walls_sd/stucco08e_norm, invertColor(textures/egypt_walls_sd/stucco08e_disp) )
	specularmap			textures/egypt_walls_sd/stucco08e_spec
	
}

textures/egypt_walls_sd/white01
{
    qer_editorimage 	textures/egypt_walls_sd/white01
	diffusemap			textures/egypt_walls_sd/white01
	bumpmap        		displacemap( textures/egypt_walls_sd/white01_norm, invertColor(textures/egypt_walls_sd/white01_disp) )
	specularmap			textures/egypt_walls_sd/white01_spec
	
}

textures/egypt_walls_sd/white01var1
{
    qer_editorimage 	textures/egypt_walls_sd/white01var1
	diffusemap			textures/egypt_walls_sd/white01var1
	bumpmap        		displacemap( textures/egypt_walls_sd/white01var1_norm, invertColor(textures/egypt_walls_sd/white01var1_disp) )
	specularmap			textures/egypt_walls_sd/white01var1_spec
	
}

textures/egypt_walls_sd/white01var2
{
    qer_editorimage 	textures/egypt_walls_sd/white01var2
	diffusemap			textures/egypt_walls_sd/white01var2
	bumpmap        		displacemap( textures/egypt_walls_sd/white01var2_norm, invertColor(textures/egypt_walls_sd/white01var2_disp) )
	specularmap			textures/egypt_walls_sd/white01var2_spec
	
}

textures/egypt_walls_sd/white01var3
{
    qer_editorimage 	textures/egypt_walls_sd/white01var3
	diffusemap			textures/egypt_walls_sd/white01var3
	bumpmap        		displacemap( textures/egypt_walls_sd/white01var3_norm, invertColor(textures/egypt_walls_sd/white01var3_disp) )
	specularmap			textures/egypt_walls_sd/white01var3_spec
	
}

textures/egypt_walls_sd/wood_c05
{
    qer_editorimage 	textures/egypt_walls_sd/wood_c05
	diffusemap			textures/egypt_walls_sd/wood_c05
	bumpmap        		displacemap( textures/egypt_walls_sd/wood_c05_norm, invertColor(textures/egypt_walls_sd/wood_c05_disp) )
	specularmap			textures/egypt_walls_sd/wood_c05_spec
	
}

textures/egypt_walls_sd/wood_c06
{
    qer_editorimage 	textures/egypt_walls_sd/wood_c06
	diffusemap			textures/egypt_walls_sd/wood_c06
	bumpmap        		displacemap( textures/egypt_walls_sd/wood_c06_norm, invertColor(textures/egypt_walls_sd/wood_c06_disp) )
	specularmap			textures/egypt_walls_sd/wood_c06_spec
	
}

textures/egypt_walls_sd/wood_test
{
    qer_editorimage 	textures/egypt_walls_sd/wood_test
	diffusemap			textures/egypt_walls_sd/wood_test
	bumpmap        		displacemap( textures/egypt_walls_sd/wood_test_norm, invertColor(textures/egypt_walls_sd/wood_test_disp) )
	specularmap			textures/egypt_walls_sd/wood_test_spec
	
}