// levelshots.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 27 total shaders

levelshots/automap_mask
{
	nopicmip
	nocompress
	nomipmaps
	{
		map gfx/2d/compass_mask.tga
		alphafunc GE128	
	}
}

levelshots/etx_fueldump_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/fueldump_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/etx_fueldump_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/fueldump_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/etx_goldrush_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/goldrush_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/etx_goldrush_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/goldrush_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/etx_railgun_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/railgun_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/etx_railgun_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/railgun_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/etx_battery_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/battery_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/etx_battery_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/battery_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/etx_oasis_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/oasis_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/etx_oasis_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/oasis_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/etx_radar_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/radar_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/etx_radar_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/radar_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

