// stone.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

textures/stone/mxdebri0_riverbed
{

	qer_editorimage textures/stone/mxdebri0_riverbed
	diffusemap		textures/stone/mxdebri0_riverbed
	bumpmap         displacemap( textures/stone/mxdebri0_riverbed_normal, invertColor(stone/mxdebri0_riverbed_parallax) )
	specularmap		textures/stone/mxdebri0_riverbed_spec
	
}

textures/stone/mxrock1aa
{
	surfaceparm grasssteps
	implicitMap -
	
	er_editorimage textures/stone/mxrock1aa
	diffusemap		textures/stone/mxrock1aa
	bumpmap         displacemap( textures/stone/mxrock1aa_normal, invertColor(stone/mxrock1aa_parallax) )
	specularmap		textures/stone/mxrock1aa_spec
	
	
}

textures/stone/mxrock3_a
{

	qer_editorimage textures/stone/mxrock3_a
	diffusemap		textures/stone/mxrock3_a
	bumpmap         displacemap( textures/stone/mxrock3_a_normal, invertColor(stone/mxrock3_a_parallax) )
	specularmap		textures/stone/mxrock3_a_spec
	
}

textures/stone/mxrock3h_snow
{

	qer_editorimage textures/stone/mxrock3h_snow
	diffusemap		textures/stone/mxrock3h_snow
	bumpmap         displacemap( textures/stone/mxrock3h_snow_normal, invertColor(stone/mxrock3h_snow_parallax) )
	specularmap		textures/stone/mxrock3h_snow_spec
	
}

textures/stone/mxsnow2
{

	qer_editorimage textures/stone/mxsnow2
	diffusemap		textures/stone/mxsnow2
	bumpmap         displacemap( textures/stone/mxsnow2_normal, invertColor(stone/mxsnow2_parallax) )
	specularmap		textures/stone/mxsnow2_spec
	
}

textures/stone/mxsnow3
{

	qer_editorimage textures/stone/mxsnow3
	diffusemap		textures/stone/mxsnow3
	bumpmap         displacemap( textures/stone/mxsnow3_normal, invertColor(stone/mxsnow3_parallax) )
	specularmap		textures/stone/mxsnow3_spec
	
}