// wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 26 total shaders

textures/wood/wood_c01
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_c01
	diffusemap			textures/wood/wood_c01
	bumpmap        		displacemap( textures/wood/wood_c01_norm, invertColor(textures/wood/wood_c01_disp) )
	specularmap			textures/wood/wood_c01_spec 
}

textures/wood/wood_m01_usat
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m01_usat
	diffusemap			textures/wood/wood_m01_usat
	bumpmap        		displacemap( textures/wood/wood_m01_usat_norm, invertColor(textures/wood/wood_m01_usat_disp) )
	specularmap			textures/wood/wood_m01_usat_spec 
}

textures/wood/wood_m02 //same hight-maps as wood_m01_usat but OWN specular
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m02
	diffusemap			textures/wood/wood_m02
	bumpmap        		displacemap( textures/wood/wood_m01_usat_norm, invertColor(textures/wood/wood_m01_usat_disp) )
	specularmap			textures/wood/wood_m02_spec 
}

textures/wood/wood_m02a //same special-maps as wood_m01_usat
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m02a
	diffusemap			textures/wood/wood_m02a
	bumpmap        		displacemap( textures/wood/wood_m01_usat_norm, invertColor(textures/wood/wood_m01_usat_disp) )
	specularmap			textures/wood/wood_m01_usat_spec 
}

textures/wood/wood_m05
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05_usata //missing
{
	surfaceparm woodsteps
	implicitMap -
}


textures/wood/wood_m05a_usat //crossbar
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m05a_usat
	diffusemap			textures/wood/wood_m05a_usat
	bumpmap        		displacemap( textures/wood/wood_m05a_usat_norm, invertColor(textures/wood/wood_m05a_usat_disp) )
	specularmap			textures/wood/wood_m05a_usat_spec 
}

textures/wood/wood_m05a_usat_snow //missing
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usata 
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m05a_usata
	diffusemap			textures/wood/wood_m05a_usata
	bumpmap        		displacemap( textures/wood/wood_m05a_usata_norm, invertColor(textures/wood/wood_m05a_usata_disp) )
	specularmap			textures/wood/wood_m05a_usata_spec
}

textures/wood/wood_m05a_usata_dm
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m05a_usata_dm
	diffusemap			textures/wood/wood_m05a_usata_dm
	bumpmap        		displacemap( textures/wood/wood_m05a_usata_norm, invertColor(textures/wood/wood_m05a_usata_disp) )
	specularmap			textures/wood/wood_m05a_usata_spec
}

textures/wood/wood_m06
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06a
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06b
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m08
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m08_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m09
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m09_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m11
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12a
{
	qer_editorimage textures/wood/wood_m12.tga
	surfaceparm woodsteps
	implicitMap textures/wood/wood_m12.tga
}

textures/wood/wood_m13
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m13_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m16
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m16cm
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m18
{
	surfaceparm woodsteps
	implicitMap -
}
