// wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 26 total shaders

textures/wood/wood_c01
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_c01
	diffusemap			textures/wood/wood_c01
	bumpmap        		displacemap( textures/wood/wood_c01_norm, invertColor(textures/wood/wood_c01_disp) )
	specularmap			textures/wood/wood_c01_spec 
}

textures/wood/wood_m01_usat
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m01_usat
	diffusemap			textures/wood/wood_m01_usat
	bumpmap        		displacemap( textures/wood/wood_m01_usat_norm, invertColor(textures/wood/wood_m01_usat_disp) )
	specularmap			textures/wood/wood_m01_usat_spec 
}

textures/wood/wood_m02 //same hight-maps as wood_m01_usat but OWN specular
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m02
	diffusemap			textures/wood/wood_m02
	bumpmap        		displacemap( textures/wood/wood_m01_usat_norm, invertColor(textures/wood/wood_m01_usat_disp) )
	specularmap			textures/wood/wood_m02_spec 
}

textures/wood/wood_m02a //same special-maps as wood_m01_usat
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m02a
	diffusemap			textures/wood/wood_m02a
	bumpmap        		displacemap( textures/wood/wood_m01_usat_norm, invertColor(textures/wood/wood_m01_usat_disp) )
	specularmap			textures/wood/wood_m01_usat_spec 
}

textures/wood/wood_m05
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05_usata //missing
{
	surfaceparm woodsteps
	implicitMap -
}


textures/wood/wood_m05a_usat //crossbar
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m05a_usat
	diffusemap			textures/wood/wood_m05a_usat
	bumpmap        		displacemap( textures/wood/wood_m05a_usat_norm, invertColor(textures/wood/wood_m05a_usat_disp) )
	specularmap			textures/wood/wood_m05a_usat_spec 
}

textures/wood/wood_m05a_usat_snow //missing
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usata 
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m05a_usata
	diffusemap			textures/wood/wood_m05a_usata
	bumpmap        		displacemap( textures/wood/wood_m05a_usata_norm, invertColor(textures/wood/wood_m05a_usata_disp) )
	specularmap			textures/wood/wood_m05a_usata_spec
}

textures/wood/wood_m05a_usata_dm
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m05a_usata_dm
	diffusemap			textures/wood/wood_m05a_usata_dm
	bumpmap        		displacemap( textures/wood/wood_m05a_usata_norm, invertColor(textures/wood/wood_m05a_usata_disp) )
	specularmap			textures/wood/wood_m05a_usata_spec
}

textures/wood/wood_m06a
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m06a
	diffusemap			textures/wood/wood_m06a
	bumpmap        		displacemap( textures/wood/wood_m06a_norm, invertColor(textures/wood/wood_m06a_disp) )
	specularmap			textures/wood/wood_m06a_spec
}

//Everything between 6 and 12 is misteriously absent

textures/wood/wood_m12
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m12
	diffusemap			textures/wood/wood_m12
	bumpmap        		displacemap( textures/wood/wood_m12_norm, invertColor(textures/wood/wood_m12_disp) )
	specularmap			textures/wood/wood_m12_spec
}

textures/wood/wood_m15 //zelfde special maps als wood_m12
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m15
	diffusemap			textures/wood/wood_m15
	bumpmap        		displacemap( textures/wood/wood_m12_norm, invertColor(textures/wood/wood_m12_disp) )
	specularmap			textures/wood/wood_m12_spec
}

textures/wood/wood_m12_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12a //whatever the difference migth be with _m12
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m12
	diffusemap			textures/wood/wood_m12
	bumpmap        		displacemap( textures/wood/wood_m12_norm, invertColor(textures/wood/wood_m12_disp) )
	specularmap			textures/wood/wood_m12_spec
}

textures/wood/wood_m13 //same specialmaps as _m13_usat
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m13
	diffusemap			textures/wood/wood_m13
	bumpmap        		displacemap( textures/wood/wood_m13_usat_norm, invertColor(textures/wood/wood_m13_usat_disp) )
	specularmap			textures/wood/wood_m13_usat_spec
}

textures/wood/wood_m13_usat
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m13_usat
	diffusemap			textures/wood/wood_m13_usat
	bumpmap        		displacemap( textures/wood/wood_m13_usat_norm, invertColor(textures/wood/wood_m13_usat_disp) )
	specularmap			textures/wood/wood_m13_usat_spec
}

textures/wood/wood_m16
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m16
	diffusemap			textures/wood/wood_m16
	bumpmap        		displacemap( textures/wood/wood_m16_norm, invertColor(textures/wood/wood_m16_disp) )
	specularmap			textures/wood/wood_m16_spec
}

textures/wood/wood_m16cm //the SAME as _m16, one wonders what they were thinking
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m16
	diffusemap			textures/wood/wood_m16
	bumpmap        		displacemap( textures/wood/wood_m16_norm, invertColor(textures/wood/wood_m16_disp) )
	specularmap			textures/wood/wood_m16_spec
}

textures/wood/wood_m18
{
	surfaceparm woodsteps
	
	qer_editorimage 	textures/wood/wood_m18
	diffusemap			textures/wood/wood_m18
	bumpmap        		displacemap( textures/wood/wood_m18_norm, invertColor(textures/wood/wood_m18_disp) )
	specularmap			textures/wood/wood_m18_spec
}
